var extraLevels = [
  {'diff': 0, 'creator': 'RedMountain', 'funcName': 'redMountain4', 'levelName': 'calc. evolution'},
  {'diff': 3, 'creator': 'PillowPrism', 'funcName': 'PillowLevelTest7', 'levelName': 'Fixed Position!'},
  {'diff': 3, 'creator': 'Spotky1004', 'funcName': 'levelPingPong', 'levelName': 'ping pong!'},
  {'diff': 1, 'creator': 'Spotky1004', 'funcName': 'levelTest', 'levelName': 'test map'},
  {'diff': 2, 'creator': 'Spotky1004', 'funcName': 'levelTest2', 'levelName': 'bumping square'},
  {'diff': 4, 'creator': 'Spotky1004', 'funcName': 'levelTextParse', 'levelName': 'Text to Particle'},
  {'diff': 3, 'creator': 'Spotky1004', 'funcName': 'levelTest3', 'levelName': 'tracing square'},
  {'diff': 3, 'creator': 'Spotky1004', 'funcName': 'levelTest4', 'levelName': 'blinking square'},
  {'diff': 0, 'creator': 'Spotky1004', 'funcName': 'levelIncremental', 'levelName': 'increment'},
  {'diff': 3, 'creator': 'PillowPrism', 'funcName': 'levelPillowTest', 'levelName': 'bottom aviod'},
  {'diff': 1, 'creator': 'RedMountain', 'funcName': 'redMountain2', 'levelName': 'wave!'},
  {'diff': 0, 'creator': 'Spotky1004', 'funcName': 'levelIcon', 'levelName': 'favicon'},
  {'diff': 0, 'creator': 'Spotky1004', 'funcName': 'levelWallTest', 'levelName': 'sturdy wall'},
  {'diff': 2, 'creator': 'Spotky1004', 'funcName': 'onDeleteEventTest', 'levelName': 'test boom'},
  {'diff': 7, 'creator': 'Spotky1004', 'funcName': 'lagTest', 'levelName': '2000 particles'},
  {'diff': 3, 'creator': 'Spotky1004', 'funcName': 'levelCalc', 'levelName': 'math!'},
  {'diff': 0, 'creator': 'Spotky1004', 'funcName': 'sidesTest', 'levelName': 'polygons'},
  {'diff': 0, 'creator': 'Spotky1004', 'funcName': 'circleTest', 'levelName': 'circle'},
  {'diff': 0, 'creator': 'Spotky1004', 'funcName': 'pointTest', 'levelName': 'arrow'},
  {'diff': 0, 'creator': 'Spotky1004', 'funcName': 'levelPlayer', 'levelName': 'player grid'},
];
